app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_hecho:
    resource: "@AppBundle/Resources/config/routing/hecho.xml"
    prefix:   /hecho

app_tag:
        resource: "@AppBundle/Resources/config/routing/tag.xml"
        prefix:   /tag

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

ef_connect:
    path:  /efconnect/{instance}/{homeFolder}
    defaults: { _controller: FMElfinderBundle:ElFinder:load, instance: default, homeFolder: '' }
    
elfinder:
    path: /files/{instance}/{homeFolder}
    defaults: { _controller: FMElfinderBundle:ElFinder:show, instance: default, homeFolder: '' }
